apiVersion: v1
kind: Service

metadata:
  name: loginapi-service
  namespace: loginapi

spec:
  selector:
    app: loginapi

  type: NodePort

  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30080